url: "https://asean.hp.gbif-test.org" # the base hostname & protocol for your staging site, e.g. https://example.hp.gbif-uat.org

useSharedLibrary: true # Use the new component library
testSite: true #style the site to show that it is a test site
graphqlEndpoint: "https://graphql.gbif-test.org/graphql" # for use with e.g. new stories from GBIF.org

include: # include languages that are excluded in production. this is useful for testing purposes
  - bn/ # Brunei Darussalam
  - id/ # Indonesia
  - kh/ # Cambodia
  - la/ # Lao PDR
  - mm/ # Myanmar
  - my/ # Malaysia
  - ph/ # Philippines
  - sg/ # Singapore
  - th/ # Thailand
  - tl/ # Timor-Leste
  - vn/ # Vietnam
