# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: ASEAN Biodiversity Dashboard Hosted Portal # the title of your site should go here
#title: A+BIGNET # the title of your site should go here
email: cbelloran@aseanbiodiversity.org
description: >- # this means to ignore newlines (until baseurl:)
  The ASEAN Biodiversity Dashboard is a regional data platform developed to support the monitoring and 
  reporting of biodiversity-related indicators across ASEAN Member States. It consolidates and visualizes 
  biodiversity data from national and global sources, helping track progress toward global commitments such 
  as the Kunming-Montreal Global Biodiversity Framework (KM-GBF) and the Sustainable Development Goals (SDGs). 
  The dashboard enables policymakers, researchers, and the public to access key information on species, 
  ecosystems, protected areas, and conservation efforts in the ASEAN region, promoting informed 
  decision-making and regional collaboration.
baseurl: "" # the subpath of your site, e.g. /blog https://abignet.aseanbiodiversity.org/
url: "https://dashboard-hp.aseanbiodiversity.org" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: jekyllrb
github_username:  jekyll

# Build settings
theme: minima
plugins:
  - jekyll-feed
  - jekyll-remote-theme

remote_theme: gbif/jekyll-hp-base-theme

algae.hideHelper: true

# for usage in the standard privacy layout
privacy:
  name: Kit Elloran
  domain: https://dashboard-hp.aseanbiodiversity.org
  contactEmail: cbelloran@aseanbiodiversity.org
  helpdeskEmail: cbelloran@aseanbiodiversity.org

# The text for the terms can be changed by adding translations for 'terms', 'acceptTerms' and 'rejectTerms' in `/_data/translations.yml`.
siteMeasurements:
  enable: false # When enabled there will be a popup asking the user for their consent. If they accept then the function "attachMeasurements" will be called. You can overwrite this function by adding a file `/_includes/js/measure.js` and replace the function.
  GA_ID: "G-WGZ4M2QG3Z" # Your Google analytics ID. Sometimes they start with UA-XXXXX-X other times with G-XXXXXXXX depending on how you set it up
  termsVersion: "2025-07-06" # A version number for your terms. If you change this, then the users will see the popup again asking them to confirm/reject anew.

useSharedLibrary: true
algae:
  rootLang: en
  # latestPostLimit: 2
  logo: /assets/images/logo/dashboardlogo2-2.png     # Logo in navbar, will be displayed with 28px height
  logoAndTitle: false           # include the title next to the logo
  archive_permalink: https://dashboard.aseanbiodiversity.org/       # /news/ Permalink of page using archive.html layout, required when using post categories
  style:
      square: false               # Should corners be square or rounded
    colors:
      primary: "#ff581d"          # Primary color of your brand. Use HEX code. Used for buttons and links
      links: "#fa5e97"          # What color should links have. Use a HEX code. DEfault is primary color. 
    coloredHeadlineLinks: false   # If a headline is a link, then use the link color. Default is true. 
    navbar:                         # RELATED TO NAVIGATION BAR
      brandBackground: yellow     # Define a custom background for the logo/title in the top navigation bar
      color: "#20a42c"             # What color should the navbar be?
     # hasWhiteText: true          # Should the text color be white?

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

exclude:
  - _posts/es # if we start adding posts this should be added until they are ready
  - .LICENSE
  - .netlify.toml
  - .README.md

permalink: pretty # will strip extensions like .html from urls

defaults:
  - scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "page"
      lang: en
  - scope:
      path: "_posts" # an empty string here means all files in the project
    values:
      layout: "post"
      permalink: "/post/:year/:slug/"   # Use /post/yyyy/{filename}/ as permalink for all posts
  - scope:
      path: ""
    values:
      lang: en
  - scope:
      path: "mm/"
    values:
      lang: mm
  - scope:
      path: "_posts/mm"
    values:
      layout: "post"
      permalink: "/mm/post/:year/:slug/"
      lang: mm
  - scope:
      path: "kh/"
    values:
      lang: kh
  - scope:
      path: "_posts/kh"
    values:
      layout: "post"
      permalink: "/kh/post/:year/:slug/"
      lang: kh
  - scope:
      path: "id/"
    values:
      lang: id
  - scope:
      path: "_posts/id"
    values:
      layout: "post"
      permalink: "/id/post/:year/:slug/"
      lang: id
  - scope:
      path: "la/"
    values:
      lang: la
  - scope:
      path: "_posts/la"
    values:
      layout: "post"
      permalink: "/la/post/:year/:slug/"
      lang: la
  - scope:
      path: "my/"
    values:
      lang: my
  - scope:
      path: "_posts/my"
    values:
      layout: "post"
      permalink: "/my/post/:year/:slug/"
      lang: my
  - scope:
      path: "th/"
    values:
      lang: th
  - scope:
      path: "_posts/th"
    values:
      layout: "post"
      permalink: "/th/post/:year/:slug/"
      lang: th
  - scope:
      path: "vn/"
    values:
      lang: vn
  - scope:
      path: "_posts/vn"
    values:
      layout: "post"
      permalink: "/vn/post/:year/:slug/"
      lang: vn
